all:
  children:
    bastion:
      hosts:
        bastion-host:
          ansible_host: 18.234.1.206

    k3s_cluster:
      hosts:
        k3s-master:
          ansible_host: 10.0.10.191

    pdf_worker:
      hosts:
        worker-node:
          ansible_host: 10.0.20.129

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/pdfroar-keypair.pem
