apiVersion: 1

datasources:
  - name: Prometheus-pdfRoar
    type: prometheus
    access: proxy
    url: http://host.docker.internal:8000
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      timeInterval: 5s
