apiVersion: 1

datasources:
  - name: Prometheus-pdfRoar
    type: prometheus
    access: proxy
    url: http://pdfroar-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s
